version: '3.8'

name: qualgo

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
    - .env
    command: yarn start:dev
    ports:
      - 3000:3000
    links:
        - database
        - redis
    depends_on:
        - database  
        - redis
  database:
      container_name: db
      image: mysql:8.0
      restart: unless-stopped
      ports:
          - "${MYSQL_PORT}:3306"
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_HOST: ${MYSQL_HOST}    
      volumes:
        - mysql:/var/lib/mysql

  redis:
      container_name: redis
      image: redis:latest
      ports:
        - "${REDIS_PORT}:6379"
      command: redis-server --requirepass ${REDIS_PASSWORD}
      volumes:
        - redis:/data
      restart: unless-stopped
      environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  mysql:   
  redis:     
