version: '3.8'

name: qualgo

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
    - .env
    command: yarn start:dev
    ports:
      - 3000:3000
    links:
        - database
    depends_on:
        - database  
  database:
      container_name: db
      image: mysql:8.0
      restart: unless-stopped
      ports:
          - "${MYSQL_PORT}:3306"
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_HOST: ${MYSQL_HOST}    
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql:        
