name: Qualgo CI

on:
    pull_request:
      types: [ opened, synchronize, reopened ]
    push:
        branches:
            - main

jobs:
  be-eslint-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'

    - name: Install dependencies

      run: yarn install

    - name: Check code format

      run: |
            yarn lint-staged -q

            yarn check:code

